version: '3.8'

services:
    # API сервер
    api:
        build: 
            context: .
            dockerfile: SecureAuth.Api/Dockerfile
        #ports:
        #    - "8001:8080" # внешний порт 8001 -> внутренний порт 8080
        depends_on:
            - db
            - redis
        volumes:
            - apidata:/root/.aspnet/DataProtection-Keys
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - Jwt__Key=Super_secure_ULTRA_secure_password_for_my_jwt_KEEP_IT_SAFE!!!
            - Jwt__Issuer=MyAuthServer
            - Jwt__Audience=MyApiClient
            - ConnectionStrings__DefaultConnection=Host=db;Database=secureauthdb;Username=secureauthuser;Password=secureauthpassword
            - ASPNETCORE_URLS=http://+:8080
            - Redis_Host=redis
    
    # WebApp сервер
    webapp:
        build: 
            context: .
            dockerfile: SecureAuth.WebApp/Dockerfile
        #ports:
        #    - "8002:8080" # внешний порт 8002 -> внутренний порт 8080
        depends_on:
            - db
            - redis
        volumes:
            - webappkeys:/app/keys # Вечное хранилище для ключей ASP.NET Core Data Protection
            - webappdata:/root/.aspnet/DataProtection-Keys # Вечное хранилище для DataProtection-Keys (для совместимости)
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - Jwt__Key=Super_secure_ULTRA_secure_password_for_my_jwt_KEEP_IT_SAFE!!!
            - Jwt__Issuer=MyAuthServer
            - Jwt__Audience=MyApiClient
            - ConnectionStrings__DefaultConnection=Host=db;Database=secureauthdb;Username=secureauthuser;Password=secureauthpassword
            - ASPNETCORE_URLS=http://+:8080
            - Redis_Host=redis

    # NGINX-сервер - точка входа для HTTPS-трафика и применения Rate Limiting
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_proxy
        ports:
            # для http
            - "80:80" # внешний порт 80 -> внутренний порт 80 
            # для https
            - "443:443" # внешний порт 443 -> внутренний порт 443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # настройки NGINX
            - ./nginx/certs:/etc/nginx/certs:ro # папка для SSL-сертификатов
        depends_on:
            - api
            - webapp
            - redis

    # Redis - сервер счетчиков для DoS-защиты (Rate Limiting)
    redis:
        image: redis:latest
        container_name: redis_cache

    # База данных PostgreSQL
    db:
        image: postgres:15
        restart: always
        environment:
            - POSTGRES_DB=secureauthdb
            - POSTGRES_USER=secureauthuser
            - POSTGRES_PASSWORD=secureauthpassword
        ports:
            - "5432:5432" # внешний порт 5432 -> внутренний порт 5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        # external: true 
        name: secure_auth_postgres_prod_data
    apidata:
    webappkeys:
    webappdata:
